name: Deploy to S3

inputs:
  node_version:
    required: true
  s3_bucket:
    required: true
  is_prod:
    required: true
  cf_dist_id:
    required: false
    default: ''
  invalidate_paths:
    required: false
    default: '/*'
  

runs:
  using: composite
  steps:
    - run: npm ci
      shell: bash
    - run: npm run build
      shell: bash
    - name: Sync to S3
      run: aws s3 sync build/ s3://${{ inputs.s3_bucket }} --delete
      shell: bash

    - name: Invalidate CloudFront (prod only)
      if: ${{ inputs.is_prod == 'true' && inputs.cf_dist_id != '' }}
      run: >-
        aws cloudfront create-invalidation
        --distribution-id ${{ inputs.cf_dist_id }}
        --paths "${{ inputs.invalidate_paths }}"
      shell: bash